django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path("admin/", admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path("__reload__/", include("django_browser_reload.urls")), #for refreshing the page
    path('zonework/', include('zonework.urls')),
    path('scraper/', include('scraper.urls')),
    path("", include("pages.urls")),
    
]

pages/urls.py
from django.urls import path

from .views import HomePageView

urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
]

zonework_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('zonework_app.urls')),
    path("admin/", admin.site.urls),
]

learning_app/models.py
from django.db import models
from django.conf import settings


class Session(models.Model):
    class Assessment(models.TextChoices):
        UNDERSTAND = "Understand", "Understand"
        NOT_YET = "Not Yet", "Not Yet"

    subject = models.CharField(max_length=100)
    assessment = models.CharField(
        max_length=20, choices=Assessment.choices, default=Assessment.NOT_YET
    )
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.subject

scraper/models.py
from django.db import models
from zonework.models import Subject, Evaluation

class Video(models.Model):
    url = models.URLField(unique=True)
    title = models.CharField(max_length=200)
    description = models.TextField()
    chapters = models.TextField(null=True, blank=True)


    def __str__(self):
        return self.title
    
class Video_Chapter(models.Model):
    video = models.ForeignKey(Video, on_delete=models.CASCADE)
    timestamp = models.CharField(max_length=10)
    title = models.CharField(max_length=200)
    chapter = models.TextField(null=True, blank=True)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return f"{self.timestampself} - {self.title}"

zonework/models.py
from django.db import models
from django.urls import reverse

class Evaluation(models.Model):
    # Evaluation model
    # Fields: id, name, description, start_date, end_date, created_at, updated_at
    subject = models.ForeignKey('Subject', on_delete=models.CASCADE)
    description = models.TextField()
    understand = models.BooleanField(default=False)
    not_yet = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    student = models.ForeignKey('accounts.CustomUser', on_delete=models.CASCADE, null=True)


    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return self.description
    
    def get_absolute_url(self):
        return reverse('evaluation_detail')

class Subject(models.Model):
    title = models.CharField(max_length=200)
    published_date = models.DateTimeField(blank=True, null=True)
    author = models.CharField(max_length=200)
    
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('subject_detail', args=[str(self.id)])
    

learning_app/views.py
from django.views.generic import ListView, CreateView
from .models import Session


class SummaryListView(ListView):
    model = Session
    template_name = "summary.html"

class SubjectCreateView(CreateView):
    model = Session
    template = "subject.html"
    fields = ["subject"]

class HomeListView(ListView):
    model = Session
    template_name = "home.html"

templates/about.html
{% extends "base.html" %}

{% block content %}
<h3>this is the about page</h3>




{% endblock content %}

templates/add_video.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Scraper{% endblock title %}

{% block content %}
<body>
    <h2>Scraper</h2>

    <form method="post" action="{% url 'add_video' %}">
        {% csrf_token %}
        <label for="url">YouTube URL:</label>
        <input type="text" name="url" required>
        <button type="submit">Scrape</button>
    </form>

    <div class="card">
        <p>Title: {{ video.title }}</p>
        <p>Description: {{ video.description }}</p>
        <p>Chapters: {{ video.chapter }}</p>
    </div>
</body>


{% endblock content %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}Zonework{% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/base.css' %}"/>
    
</head>
<body>
    <header>
        <!-- Your header content goes here -->
    </header>


<!--nav bar -->
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <a class="navbar-brand" href="{% url 'home' %}">Zonework</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        </button>
        <div class="container-fluid">
            <ul class="navbar-nav">
                <li class="nav-item active">
                <a class="nav-link" href=#>About</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'subject_list' %}">Learn</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'dashboard' %}">Dashboard</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'add_video' %}">Add Class</a>
                </li>
    <!-- user login & logout -->
        </ul>
        <div class="dropdown text-end">
            <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" id="dropdownUser1"
            data-bs-toggle="dropdown" aria-expanded="false">
            {{ user.username }}
            </a>
            <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1">
            <li><a class="dropdown-item" href="{% url 'password_change' %}">
                Change password</a></li>
            <li><a class="dropdown-item" href="{% url 'logout' %}">Log Out</a></li>
            </ul>
        </div>
        
        {% else %}
        </ul>
        <div class="text-end">
            <a href="{% url 'login' %}" class="btn btn-outline-primary me-2">
            Log In</a>
            <a href="{% url 'signup' %}" class="btn btn-primary">Sign Up</a>
        </div>
        {% endif %}
        </div>
    
    </nav>

    <main>
        {% block content %}
        <!-- This is a placeholder for the content of each page -->
        {% endblock %}
    </main>

    <footer>
        <!-- Your footer content goes here -->
    </footer>

    <script src="{% static 'js/base.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
</body>
</html>

templates/dashboard.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Dashboard{% endblock title %}
{% block content %}

<body>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <h2>Dashboard</h2>

    <!-- Your HTML content -->

    <div class="container">
        <div class="row">
            <div class="col">
                <canvas id="myChart" width="200" height="100"></canvas>
            </div>
        </div>
    </div>

    
    <script>
        // Ensure JavaScript executes after the DOM is loaded
        document.addEventListener("DOMContentLoaded", function () {
            var chartData = {{ chartData|safe }};
            console.log(chartData);
            console.log(chartData.evals);
            console.log(chartData.understand_evals);
            console.log(chartData.not_yet_evals);
            var ctx = document.getElementById('myChart').getContext('2d');
            var myChart = new Chart(ctx, {
                type: 'bar',
                data: {
                    labels: chartData.labels,
                    datasets: [{
                        label: 'Understand',
                        data: chartData.understand_evals,
                        backgroundColor: 'rgba(0, 128, 0, 0.2)',
                        borderColor: 'rgba(0, 128, 0, 1)',
                        borderWidth: 1
                    }, {
                        label: 'Not Yet',
                        data: chartData.not_yet_evals,
                        backgroundColor: 'rgba(75, 192, 192, 0.2)',
                        borderColor: 'rgba(75, 192, 192, 1)',
                        borderWidth: 1
                    }]
                },
                options: {
                    scales: {
                        x: {
                            stacked: true
                        },
                        y: {
                            stacked: true,
                            beginAtZero: true
                        }
                    }
                }
            });
        });
    </script>
</body>
{% endblock content %}

templates/entry.html
{% extends "base.html" %}

{% block title %}session-entry{% endblock title %}

{% block content %}
<div>
    <h2>Enter subject here</h2>
      <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-success ml-2" type="submit">Start</button>
      </form>
    </div>
{% endblock content %}

templates/home.html
<!-- FILEPATH: /Users/kdh/Documents/developer/Git/zw_4/templates/home.html -->

{% extends 'base.html' %}

{% block title %}Home{% endblock title %}


{% block content %}
{% if user.is_authenticated %}
    <h1>Welcome to the Student Home Page</h1>
    <p>This is the content for the home page.</p>
    <!-- <img src="path/to/image.jpg" alt="Image"> -->
    <p><a href="{% url 'logout' %}">Log Out</a></p>
{% else %}
    <p>You are not logged in.</p>
    <a href="{% url 'login' %}">Log In</a>
    <a href="{% url 'signup' %}">Sign Up</a>
{% endif %}

{% endblock content %}

templates/learning.html
{% extends "base.html" %} {% load crispy_forms_tags %} 

{% block styles %}
<style>
.form-row {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 0.5rem;
}

.update-btn {
  padding: 0.25rem 0.5rem;
  font-size: 0.8rem;
}

.table td,
.table th {
  padding: 0.5rem;
}

#id_text {
  width: 200px;
  height: 34px;
}

#id_subject {
  width: 200px;
  height: 34px;
}

</style>
{% endblock %}

{% block content %}
  


  <div>
    <h4>What are you Learning now?</h4>
    <form action="{% url 'create_learning_item' %}" method="post">
      {% csrf_token %}
      
     <div >
      <table class="table">
        <thead>
          <tr>
            <th>Subject</th>
            <th>Text</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              <input type="text" id="id_subject" name="subject">
            </td>
            <td>
              <textarea id="id_text" name="text"></textarea>
            </td>
            <td>
              <button class="btn btn-primary btn-sm update-btn" type="submit">Add</button>
            </td>
          </tr>
        </tbody>
      </table>

          <!-- <label for="id_subject" >Subject:</label>
          <input type="text" id="id_subject" name="subject">
          <label for="id_text" >Text:</label>
          <textarea id="id_text" name="text"></textarea>-->

      </div>
    </form>
  </div>
  
  <hr>

<!-- List of learning items from the database -->
<div>
  <h4>Your Registered Learning Items:</h4>
  <table class="table">
    <thead>
      <tr>
        <th>Update</th>
        <th>Status</th>
        <th>Subject</th>
        <th>Text</th>
        <th>Entry Date</th>
      </tr>
    </thead>
    <tbody>
      {% for learningitem in list_of_items reversed %}
      <tr>
        <td>
          <form action="{% url 'update_completed' learningitem.id %}" method="post">
            {% csrf_token %}
            {% if learningitem.completed %}
              <input type="checkbox" name="completed" value="ok" checked> OK
              <input type="checkbox" name="completed" value="nok"> NOK
            {% else %}
              <input type="checkbox" name="completed" value="ok"> OK
              <input type="checkbox" name="completed" value="nok" checked> NOK
            {% endif %}
            <button class="btn btn-primary btn-sm update-btn" type="submit">Update</button>
          </form>
        </td>
        <td>
          {% if learningitem.completed %} Done! {% else %} Not Done {% endif %}
        </td>
        <td>{{ learningitem.subject }}</td>
        <td>{{ learningitem.text }}</td>
        <td>{{ learningitem.entry_date }}</td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

templates/subject.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block content %}
<h3>Begin Session on {{ subject.enter_subject }}</h3>

<!-- First form for subject -->
<div> 
    <p class="enter-subject">Enter your subject</p>
    <form class="subject-form" action="" method="POST">
        
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-success ml-2" type="submit"><a href="{% url 'session' %}"></a>Start</a></button>
    </form>
</div>
<div>
    <p>enter your name</p>
    <form action="" method="post">
        {% csrf_token %}
        <a href="{% url 'session' %}">To Session page</a>
    </form>
</div>

{% endblock content %}

templates/subject_delete.html
{% extends "base.html" %}

{% block content %}
<h2>Delete</h2>
<form action="" method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete {{ subject.title }}?</p>>
    <button class="btn btn-danger ml-2" type="submit">Confirm</button>
</form>
{% endblock content %}

templates/subject_detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}ZW - {{ subject.title }}{% endblock title %}

{% block content %}

<div class="card">
    <h5 class="card-header">{{ subject.title }}</h5>
    <div class="card-body">
      <h5 class="card-title">Add Notes</h5>
      <form action="" method="post">
        {% csrf_token %}
       <div> 
        {{ form.description }}
       </div>
       <div class="zw-buttons">
        <button class="btn btn-outline-success" id="eval-button" name="understand" value="1" type="submit">Understand</button>
        <button class="btn btn-outline-success" id="eval-button" name="not_yet" value="1" type="submit">Not Yet</button>
        </div>
      </form>
    </div>
  </div>


<!-- Here is the count of total evaluations for today -->

<div class="eval-counts">
    <p>Total Evaluations: {{ subject.evaluation_set.all.count }}</p>
    <!--these are not working -->
    <p>Total Evaluations for Today: {{ both_count_today }}</p>
    <p> Total Understands: {{ understand_count }}</p>
    <p> Total Not Yets: {{ not_yet_count }}</p>

</div>


<!-- Here is the rendered evaluations -->

<div class="rendered-evaluations">

    <table class="table table-primary">
        <thead>
            <tr>
                <th>Evaluation</th>
                <th>Description</th>
                <th>Date</th>
            </tr>
        </thead>
        <tbody>
            {% for evaluation in subject.evaluation_set.all %}
                <tr>
                    <td class="eval-rendered-type 
                    {% if evaluation.understand %}
                        understand
                    {% elif evaluation.not_yet %}
                        not-yet
                    {% endif %}">
                        {% if evaluation.understand %}
                            Understand
                        {% elif evaluation.not_yet %}
                            Not Yet
                        {% endif %}
                    </td>
                    <td>
                        {{ evaluation.description }}
                    </td>
                    <td>
                        {{ evaluation.created_at }}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <hr>
</div>





<!-- here is the delete and edit buttons -->
<div>
{% if subject.student.pk == request.user.pk %}
    <p>
    <a href="{% url 'subject_edit' subject.pk %}">Edit</a>
    <a href="{% url 'subject_delete' subject.pk %}">Delete</a>
    </p>
{% endif %}
    <p>Back to <a href="{% url 'subject_list' %}">All Subjects</a>.</p>
</div>
{% endblock content %}

templates/subject_edit.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<h2>Edit</h2>
<form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button class="btn btn-info ml-2" type="submit">Update</button>
</form>
{% endblock content %}

templates/subject_list.html
{% extends 'base.html' %}
<!-- {% load crispy_forms_tags %} -->
{% load static %}

{% block title %}Subject List{% endblock title %}

{% block content %}
{% if user.is_authenticated %}
    <p><a href="{% url 'logout' %}">Log Out</a></p>

<!-- Here is the main list of subjucts  -->
    {% for subject in subject_list %}
    <div class="card" id="zw-card">
        <div class="card-header">
            <span class="fw-bold">
                <a href="{% url 'subject_detail' subject.pk %}">{{ subject.title }}</a>
            </span> &middot; 
            <span class="text-muted">by {{ subject.author }}</span>
            <a href="{{ subject.get_absolute_url }}">Keep Learning</a>
        </div>
        <div class="card-footer">
            <span class="fw-bold">
                {{ subject.total_evaluations }} Total &middot; 
                {{ subject.understand_evaluations }} Understands &middot; 
                {{ subject.not_yet_evaluations }} Not Yets
            </span>
        </div>
    </div>
    <br />
    {% endfor %}

{% else %}
    <p>You are not logged in</p>
    <a href="{% url 'login' %}">Log In</a> |
    <a href="{% url 'signup' %}">Sign Up</a>
{% endif %} 

{% endblock %}

templates/subject_new.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<h3 class="fw-bold">New Subject</h3>
<form class="flex" action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button class="btn btn-success ml-2" type="submit">Save</button>
</form>
{% endblock content %}

templates/summary.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}Summary{% endblock title %}

{% block content %}



<!-- here is the learnings recap list -->
<div>
  <h2>Here is the summary page</h2>
  {% for session in session_list %}
    <div class="session-entry">
      <h2><a href="">{{ session.subject }}</a></h2>
      <p>{{ session.body }}</p>
    </div>
  {% endfor %}
</div>

{% endblock content %}